import re
from typing import Dict, Any, List, Optional, Annotated
from dotenv import load_dotenv
from pydantic import BaseModel, Field

load_dotenv()
from langchain_core.messages import HumanMessage, AIMessage, SystemMessage, AnyMessage
from langchain_openai import ChatOpenAI
from langgraph.graph import StateGraph, START, END
from langgraph.graph.message import add_messages
from langgraph.prebuilt import ToolNode
from typing_extensions import TypedDict

from tools import extract_arxiv_id, download_arxiv_pdf_text


class PaperSummary(BaseModel):
    """Structured output for paper summary with required sections."""

    title: str = Field(description="The paper title")
    authors: str = Field(description="List of authors")
    published: str = Field(description="Publication date")
    categories: str = Field(description="Subject categories")
    url: str = Field(description="arXiv URL")
    high_level_summary: str = Field(
        description="A concise 4-5 sentence overview that captures the core contribution, main findings, and significance of the paper"
    )
    detailed_summary: str = Field(
        description="Comprehensive analysis including methodology, experiments, results, significance, strengths/limitations, and future directions"
    )
    real_world_applications: str = Field(
        description="Concrete examples of how this research can be applied in practice, including current and future applications"
    )
    abstract: str = Field(description="The original abstract from the paper")


class AgentState(TypedDict):
    messages: Annotated[list[AnyMessage], add_messages]


# Initialize the LLM
llm = ChatOpenAI(model="o3-mini")

# Define available tools
tools = [extract_arxiv_id, download_arxiv_pdf_text]

# Bind tools to the LLM
llm_with_tools = llm.bind_tools(tools)

# Create structured output LLM for final summary
llm_structured = llm.with_structured_output(PaperSummary)


def format_structured_summary(summary: PaperSummary) -> str:
    """Format the structured summary into markdown."""
    return f"""# arXiv Paper Summary

        **Title:** {summary.title}
        **Authors:** {summary.authors}
        **Published:** {summary.published}
        **Categories:** {summary.categories}
        **URL:** {summary.url}

        ## High Level Summary

        {summary.high_level_summary}

        ## Detailed Summary

        {summary.detailed_summary}

        ## Real World Applications

        {summary.real_world_applications}

        ## Abstract

        {summary.abstract}

        ---
        *Summary generated by arXiv Researcher Agent using full paper analysis*"""


def generate_structured_summary(state: AgentState):
    """Generate structured summary from conversation context."""
    messages = state["messages"]

    # Find paper content from tool results
    paper_content = None
    paper_title = None
    paper_url = None

    for message in reversed(messages):
        if hasattr(message, "content") and isinstance(message.content, list):
            # Handle tool results with multiple content blocks
            for content_block in message.content:
                if hasattr(content_block, "content"):
                    content_text = str(content_block.content)
                    if len(content_text) > 1000:  # Likely paper content
                        paper_content = content_text
                        break
        elif (
            hasattr(message, "content")
            and isinstance(message.content, str)
            and len(message.content) > 1000
        ):
            # Handle regular string content that's likely paper text
            paper_content = message.content
            break

    if not paper_content:
        return {"messages": [AIMessage(content="No paper content found to summarize.")]}

    # Extract URL from original request
    for message in messages:
        if hasattr(message, "content") and isinstance(message, HumanMessage):
            content = message.content
            if "arxiv.org" in content:
                import re

                url_match = re.search(r"https://arxiv\.org/abs/[\d.]+", content)
                if url_match:
                    paper_url = url_match.group()
                    break

    # Create prompt for structured summary
    summary_prompt = f"""Based on the following arXiv paper content, create a comprehensive structured summary. 

    Paper content:
    {paper_content}

    Fill out ALL sections completely with detailed information from the paper content."""

    # Generate structured summary
    try:
        structured_summary = llm_structured.invoke(
            [HumanMessage(content=summary_prompt)]
        )

        # Add URL if we found it
        if paper_url and not structured_summary.url:
            structured_summary.url = paper_url

        formatted_summary = format_structured_summary(structured_summary)
        return {"messages": [AIMessage(content=formatted_summary)]}

    except Exception as e:
        return {
            "messages": [
                AIMessage(content=f"Error generating structured summary: {str(e)}")
            ]
        }


def researcher(state: AgentState):
    """Main researcher node that can call tools when needed."""

    # Create a system message with instructions
    system_message = SystemMessage(
        content="""You are an expert arXiv research assistant. Your job is to help users understand academic papers from arXiv.

When a user provides:
1. An arXiv URL (like https://arxiv.org/abs/2310.06825)
2. An arXiv paper ID (like 2310.06825)
3. A request to summarize or analyze a paper

Use the available tools to extract the arxiv ID and download the pdf text. Once you have successfully downloaded the paper content, simply acknowledge that you have retrieved the paper and that a structured summary will be generated."""
    )

    # Get the messages from state
    messages = state["messages"]

    # Prepend system message if it's the first interaction
    if len(messages) == 1 and isinstance(messages[0], HumanMessage):
        messages_with_system = [system_message] + messages
    else:
        # For subsequent messages, keep the conversation flowing
        messages_with_system = messages

    # Call the LLM (which may decide to use tools)
    response = llm_with_tools.invoke(messages_with_system)

    return {"messages": [response]}


def should_generate_summary(state: AgentState) -> str:
    """Determine if we should generate structured summary."""
    last_message = state["messages"][-1]

    # If there are tool calls, go to tools
    if hasattr(last_message, "tool_calls") and last_message.tool_calls:
        return "tools"

    # Check if we have substantial paper content (indicating tools completed successfully)
    messages = state["messages"]
    has_paper_content = False

    for message in reversed(messages):
        if hasattr(message, "content"):
            if isinstance(message.content, list):
                # Check tool results
                for content_block in message.content:
                    if (
                        hasattr(content_block, "content")
                        and isinstance(content_block.content, str)
                        and len(content_block.content) > 1000
                    ):
                        has_paper_content = True
                        break
            elif (
                isinstance(message.content, str)
                and len(message.content) > 1000
                and not hasattr(message, "tool_calls")
            ):
                has_paper_content = True
                break

        if has_paper_content:
            break

    # If we have paper content, generate summary
    if has_paper_content:
        return "summary"
    else:
        return "end"


# Create the graph
workflow = StateGraph(AgentState)

# Add nodes
workflow.add_node("researcher", researcher)
workflow.add_node("tools", ToolNode(tools))
workflow.add_node("summary", generate_structured_summary)

# Add edges
workflow.add_edge(START, "researcher")
workflow.add_conditional_edges(
    "researcher",
    should_generate_summary,
    {
        "tools": "tools",
        "summary": "summary",
        "end": END,
    },
)
workflow.add_edge("tools", "researcher")
workflow.add_edge("summary", END)

# Compile the graph
app = workflow.compile()


async def run_arxiv_researcher(user_input: str) -> str:
    """Main function to run the arXiv researcher agent."""
    initial_state = {"messages": [HumanMessage(content=user_input)]}

    result = await app.ainvoke(initial_state)

    # Return the last AI message
    for message in reversed(result["messages"]):
        if isinstance(message, AIMessage):
            return message.content

    return "No response generated."


if __name__ == "__main__":
    import asyncio

    # Example usage
    async def main():
        # Test with an arXiv URL
        test_input = "Can you summarize this paper: https://arxiv.org/abs/2310.06825"

        result = await run_arxiv_researcher(test_input)
        print(result)

    asyncio.run(main())
