import re
from typing import Dict, Any, List, Optional, Annotated
from dotenv import load_dotenv

load_dotenv()
from langchain_core.messages import HumanMessage, AIMessage, SystemMessage, AnyMessage
from langchain_openai import ChatOpenAI
from langgraph.graph import StateGraph, START, END
from langgraph.graph.message import add_messages
from langgraph.prebuilt import ToolNode, tools_condition
from typing_extensions import TypedDict

from tools import extract_arxiv_id, fetch_arxiv_paper, download_arxiv_pdf_text


class AgentState(TypedDict):
    messages: Annotated[list[AnyMessage], add_messages]


# Initialize the LLM
llm = ChatOpenAI(model="o3-mini")

# Define available tools
tools = [extract_arxiv_id, download_arxiv_pdf_text]

# Bind tools to the LLM
llm_with_tools = llm.bind_tools(tools)


def researcher(state: AgentState):
    """Main researcher node that can call tools when needed."""

    # Create a system message with instructions
    system_message = SystemMessage(
        content="""You are an expert arXiv research assistant. Your job is to help users understand academic papers from arXiv.

When a user provides:
1. An arXiv URL (like https://arxiv.org/abs/2310.06825)
2. An arXiv paper ID (like 2310.06825)
3. A request to summarize or analyze a paper

You should use the available tools to extract the arxiv ID and then download the pdf text before summarizing it.

Format your final response like this:

# arXiv Paper Summary

**Title:** [paper title]
**Authors:** [authors list]
**Published:** [publication date]
**Categories:** [subject categories]
**URL:** [arxiv url]

## Analysis

[Your comprehensive analysis based on the FULL paper content, including:]
- Brief overview of the main contribution and novelty
- Detailed methodology and technical approach
- Key experiments, results, and findings
- Significance and potential impact in the field
- Strengths and limitations based on the full content
- Comparison with related work (if mentioned in paper)
- Future directions suggested by authors

## Abstract

[The original abstract]

---
*Summary generated by arXiv Researcher Agent using full paper analysis*

Since you have access to the complete paper content extracted directly from the PDF, provide deep insights that go beyond just the abstract. Focus on technical details, experimental results, and the paper's contributions to the field."""
    )

    # Get the messages from state
    messages = state["messages"]

    # Prepend system message if it's the first interaction
    if len(messages) == 1 and isinstance(messages[0], HumanMessage):
        messages_with_system = [system_message] + messages
    else:
        # For subsequent messages, keep the conversation flowing
        messages_with_system = messages

    # Call the LLM (which may decide to use tools)
    response = llm_with_tools.invoke(messages_with_system)

    return {"messages": [response]}


# Create the graph
workflow = StateGraph(AgentState)

# Add nodes
workflow.add_node("researcher", researcher)
workflow.add_node("tools", ToolNode(tools))

# Add edges
workflow.add_edge(START, "researcher")
workflow.add_conditional_edges(
    "researcher",
    tools_condition,
)
workflow.add_edge("tools", "researcher")

# Compile the graph
app = workflow.compile()


async def run_arxiv_researcher(user_input: str) -> str:
    """Main function to run the arXiv researcher agent."""
    initial_state = {"messages": [HumanMessage(content=user_input)]}

    result = await app.ainvoke(initial_state)

    # Return the last AI message
    for message in reversed(result["messages"]):
        if isinstance(message, AIMessage):
            return message.content

    return "No response generated."


if __name__ == "__main__":
    import asyncio

    # Example usage
    async def main():
        # Test with an arXiv URL
        test_input = "Can you summarize this paper: https://arxiv.org/abs/2310.06825"

        result = await run_arxiv_researcher(test_input)
        print(result)

    asyncio.run(main())
