import re
from typing import Dict, Any
import aiohttp
import xml.etree.ElementTree as ET
import fitz  # PyMuPDF

from langchain_core.tools import tool


@tool
async def extract_arxiv_id(url: str) -> str:
    """Extract arXiv ID from arXiv URL."""
    arxiv_patterns = [
        r"arxiv\.org/abs/(\d+\.\d+)",
        r"arxiv\.org/pdf/(\d+\.\d+)",
        r"(\d{4}\.\d{4,5})",
    ]

    for pattern in arxiv_patterns:
        match = re.search(pattern, url)
        if match:
            return match.group(1)

    raise ValueError(f"Could not extract arXiv ID from URL: {url}")


@tool
async def fetch_arxiv_paper(arxiv_id: str) -> Dict[str, Any]:
    """Fetch paper metadata from arXiv API."""
    api_url = f"http://export.arxiv.org/api/query?id_list={arxiv_id}"

    async with aiohttp.ClientSession() as session:
        async with session.get(api_url) as response:
            if response.status != 200:
                raise Exception(f"Failed to fetch paper: {response.status}")

            xml_content = await response.text()
            root = ET.fromstring(xml_content)

            ns = {"atom": "http://www.w3.org/2005/Atom"}
            entry = root.find("atom:entry", ns)

            if entry is None:
                raise Exception(f"Paper not found for ID: {arxiv_id}")

            title = entry.find("atom:title", ns).text.strip().replace("\n", " ")
            summary = entry.find("atom:summary", ns).text.strip().replace("\n", " ")
            published = entry.find("atom:published", ns).text

            authors = []
            for author in entry.findall("atom:author", ns):
                name = author.find("atom:name", ns).text
                authors.append(name)

            categories = []
            for category in entry.findall("atom:category", ns):
                categories.append(category.get("term"))

            return {
                "id": arxiv_id,
                "title": title,
                "authors": authors,
                "summary": summary,
                "published": published,
                "categories": categories,
                "url": f"https://arxiv.org/abs/{arxiv_id}",
            }


@tool
async def download_arxiv_pdf_text(arxiv_id: str) -> str:
    """Download the full text content of an arXiv paper as extracted from its PDF."""
    pdf_url = f"https://arxiv.org/pdf/{arxiv_id}.pdf"

    try:
        # Download the PDF as bytes
        async with aiohttp.ClientSession() as session:
            async with session.get(pdf_url, timeout=30) as response:
                if response.status != 200:
                    raise Exception(f"Failed to download PDF: status {response.status}")
                pdf_bytes = await response.read()

        # Process PDF bytes using PyMuPDF
        with fitz.open(stream=pdf_bytes, filetype="pdf") as doc:
            full_text = ""
            for page in doc:
                full_text += page.get_text("text") + "\n"

        # Basic validation
        if len(full_text) < 100:
            raise Exception("Extracted text appears too short or invalid.")

        # Truncate to avoid context window issues
        if len(full_text) > 70000:
            full_text = full_text[:70000] + "\n\n[Content truncated due to length...]"

        return full_text

    except Exception as e:
        raise Exception(f"Error extracting text from arXiv paper {arxiv_id}: {str(e)}")


@tool
def format_paper_summary(paper_data: Dict[str, Any], analysis: str) -> str:
    """Format paper data and analysis into a comprehensive summary."""

    formatted_summary = f"""# arXiv Paper Summary

**Title:** {paper_data['title']}
**Authors:** {', '.join(paper_data['authors'])}
**Published:** {paper_data['published']}
**Categories:** {', '.join(paper_data['categories'])}
**URL:** {paper_data['url']}

## Analysis

{analysis}

## Abstract

{paper_data['summary']}

---
*Summary generated by arXiv Researcher Agent*"""

    return formatted_summary
